name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Capstone
      run: |
        vcpkg install capstone:x64-windows
      shell: powershell

    - name: Configure
      run: |
        cmake -B build -A x64 `
          -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake `
          -DCMAKE_CXX_FLAGS="/I C:/vcpkg/installed/x64-windows/include" `
          -DCMAKE_EXE_LINKER_FLAGS="/LIBPATH:C:/vcpkg/installed/x64-windows/lib capstone.lib"
      shell: powershell

    - name: Build
      run: |
        cmake --build build --config Release
      shell: powershell

    - name: Copy DLL
      run: |
        Copy-Item C:/vcpkg/installed/x64-windows/bin/capstone.dll build/Release/ -ErrorAction SilentlyContinue
      shell: powershell

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: vmprotectunpacker
        path: |
          build/Release/*.exe
          build/Release/*.dll
